### ISSUE TITLE
Spec: definition of "Boolean" is ambiguous

### ISSUE THREAD

**Issue by dolmen** [Perl-Toolchain-Gang/CPAN-Meta#104]
META v2.0 can be serialized either as YAML or as JSON. Both formats have a specific type for boolean values.
Perl 5 instead accepts various values JSON/YAML types in boolean context.

The issue is that the specification suffers from the same fuzzyness as Perl 5.

For example, the section about [Boolean type](https://metacpan.org/pod/CPAN::Meta::Spec#Boolean) says:
> A Boolean is used to provide a true or false value. It must be represented as a defined value.

This is ambiguous because:
- it does not says if this is JSON's `true`/`false` or any truth value recognized by Perl 5
- a `defined value` in JSON means anything not `null` which would imply that any JSON `boolean`/`number`/`string`/`object`/`array` is allowed, including `false`, `0`, `""` (the empty string), `{}`, `[]`. 

When `Boolean` is used in the specification, the JSON `true` / `false` value are not mentioned. The [specification of `dynamic_config`](https://metacpan.org/pod/CPAN::Meta::Spec#dynamic_config) says:
> dynamic_config => 1

This implies the expected value is an integer instead of a JSON boolean.

PS: I'm writing a strict specification of META v2.0 using [JSON Schema](http://www.json-schema.org/).

**Comment by miyagawa** [comment]
I don't think it is *ambiguous*: it says that anything perl considers true or false would be accepted as long as they are defined.

I agree that it is a bit unfortunate that it also means if you want to write CPAN META file processing in languages other than perl you would need to convert these values to perly-bool converter first, but that's what the spec says and I don't see an issue here.

**Comment by Leont** [comment]
Effectively, its an `enum {0, 1}`, it may best to threat it like that.

**Comment by xdg** [comment]
I have no objection to a doc patch or implementation note to clarify that we mean "boolean" in the Perl sense, not the JSON sense.  The spec is about a *Perl* data structure.  That we happen to serialize to JSON is separate from the definition of the spec.

**Comment by dolmen** [comment]
CPAN::Meta::Validator currently has a stricter definition than just *anything that Perl 5 accepts in boolean context*.
https://metacpan.org/source/DAGOLDEN/CPAN-Meta-2.150005/lib/CPAN/Meta/Validator.pm#L833
```perl
sub boolean {
    my ($self,$key,$value) = @_;
    if(defined $value) {
        return 1    if($value =~ /^(0|1|true|false)$/);
    } else {
        $value = '<undef>';
    }
    $self->_error( "'$value' for '$key' is not a boolean value." );
    return 0;
}
```
