### ISSUE TITLE
plan for YAML and YAML::XS strict reader errors data-fixable/98042513-META.yml

### ISSUE THREAD

**Issue by rurban** [Perl-Toolchain-Gang/CPAN-Meta#106]
YAML and YAML::XS fail fatally when loading the file `t/data-fixable/98042513-META.yml`.

I've worked on all JSON and YAML backends to improve support, but in this case you 
need to make a decision.

Either turn a map value consisting of only control characters to `data-fail` (i.e. 
a non-forgiving fatal error), or wait until I implement the new NonStrict mode for 
YAML and YAML::XS. 
See https://github.com/ingydotnet/yaml-libyaml-pm/issues/44

Problem is that I couldn't fix NonStrict in the last week, so it might be too hard.

My approach was for NonStrict to ignore all control characters, leave those strings as-is or 
turn them into undef, warn about it and only when the structure cannot be parsed, fail. 
If the structure can be parsed and only a part of the string is invalid (key or value)
return the structure. So a key of undef is fatal, a value not

I have a validator pull request which tests and fixes all available JSON and YAML backends, 
and skips the failing `98042513-META.yml` tests for these 2 strict backends.
See https://github.com/Perl-Toolchain-Gang/CPAN-Meta/pull/107

**Comment by xdg** [comment]
Thank you for flagging this.  Our position has always been that only CPAN::Meta::YAML is canonical for parsing META.yml files.  Any other backend is at a user's own risk.  On that basis, I'm going to take the option to wait for YAML/YAML::XS to fix the issue on their end and close this ticket here.

(Which doesn't mean we won't take TODO tests for other backends as a helpful canary.)
