### ISSUE TITLE
2.150006-TRIAL breaks EUMM (7.18, 7.19_06)

### ISSUE THREAD

**Issue by eserte** [Perl-Toolchain-Gang/CPAN-Meta#115]
Sample report: http://www.cpantesters.org/cpan/report/bb3083e6-3c67-11e6-8388-c5095cc2a771
Statistical analysis: http://analysis.cpantesters.org/solved?distv=ExtUtils-MakeMaker-7.19_06#mod%3ACPAN%3A%3AMeta

**Comment by Leont** [comment]
"The effectiveness of trial releases has been proven by scientists"…
