### ISSUE TITLE
Fallback abstract when "unknown"

### ISSUE THREAD

**Issue by chrstphrchvz** [Perl-Toolchain-Gang/CPAN-Meta#135]
In [my list of distributions on MetaCPAN](https://metacpan.org/author/CAC), one of the distributions has an inaccurate abstract:

Release |   
-- | -- 
 Tcl-pTk-1.07 | Demonstration of Perl/Tk widgets

Presumably this is because the distribution currently fails to specify the required `abstract` field, and which I should specify in a future release if I want this fixed.

However I am curious how CPAN decides what to use instead when the abstract is "unknown", and whether it could choose a better fallback value. In this case, CPAN appears to be using the POD NAME section from a demo script (widgetTclpTk); a more logical choice would be from the module that the distribution is named for ("Tcl::pTk - Interface to Tcl/Tk with Perl/Tk compatible syntax").

**Comment by Leont** [comment]
This sounds like a MetaCPAN issue, not a CPAN-Meta issue (though I can see where the confusion comes from)

**Comment by chrstphrchvz** [comment]
Would https://github.com/metacpan/metacpan-web/issues be a better place to bring this up?

**Comment by Leont** [comment]
> Would https://github.com/metacpan/metacpan-web/issues be a better place to bring this up?

Yes, that'd be my best guess.

**Comment by chrstphrchvz** [comment]
Thanks. It turns out someone may have already reported it there: https://github.com/metacpan/metacpan-web/issues/1957
