### ISSUE TITLE
Syntax for an "identifier" (same as a string?) not clearly defined

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/CPAN-Meta#28]
I've been working on a new dist that stuffs a lot of data into the "optional_feature" section of the metadata.  Test::CPAN::Meta complained with things like: "Key 'Module Development' is not a legal identifier. (optional_features -> Module Development)"

Deep in Test::CPAN::Meta::Version I found:

    sub identifier {
        my ($self,$key) = @_;
        if(defined $key) {
            return 1    if($key && $key =~ /^([a-z][_a-z]+)$/i);    # spec 2.0 defined
    ...

...which indicates the legal syntax for an identifier.  However, I cannot find
any mention or paraphrasing of this regexp in CPAN::Meta::Spec itself -- the
closest I can find is the definition of "string", which is "[a] data element
containing a non-zero length sequence of Unicode characters".  There are a few
subtypes of Strings defined, for specific fields (such as License and URL),
but nothing pertaining to generic identifiers such as keys used in a Map.

This looks to be an oversight -- the syntax for a Map key should be explicitly
defined.

**Comment by xdg** [comment]
On the grounds that this is a problem in Test::CPAN::Meta, I'm closing this ticket.
