### ISSUE TITLE
CPAN::Meta::Converter needs to support converting metadata fragments

### ISSUE THREAD

**Issue by dagolden** [Perl-Toolchain-Gang/CPAN-Meta#41]
Per #40 we need a way of converting fragments as might be given by `meta_merge` fields into a specific version.

Something like this:

    $cmc->convert_fragment( from_version => "1.4", to_version => "2" );

This could pick off pieces of the conversion specs.  We need the "from_version" unlike the "convert" method because a fragment won't necessarily have a meta-spec field.  (Though we could mandate one, I suppose.)

Alternatively, this could be done via an option to "convert", in which case, we do need to mandate a meta-spec field, and the conversion needs to use spec fields that match the input fields.

**Comment by karenetheridge** [comment]
Is this totally done now?

**Comment by xdg** [comment]
This is done with CPAN::Meta::Merge.
