### ISSUE TITLE
Valid 1.4 license considered invalid by ::Validator

### ISSUE THREAD

**Issue by ribasushi** [Perl-Toolchain-Gang/CPAN-Meta#68]
According to [the spec](https://metacpan.org/pod/distribution/Module-Build/lib/Module/Build/API.pod#license) I can use `...a Software::License subclass name (e.g. 'Apache_2_0')...`. However, even though [the Perl_5 license](https://metacpan.org/pod/Software::License::Perl_5) exists, I get the following:

```
rabbit@Ahasver:~/devel/dbic$ grep '^license' -r META.yml 
license: Perl_5

rabbit@Ahasver:~/devel/dbic$ perl -MCPAN::Meta::Validator -MDevel::Dwarn -MYAML=LoadFile -e 'my $v = CPAN::Meta::Validator->new(LoadFile("META.yml")); Dwarn [ $v->is_valid ]; Dwarn [ $v->errors]'
[
  ""
]
[
  "License 'Perl_5' is invalid (license) [Validation: 1.4]"
]
```

Report prompted by CPANTS barfing on me with "license invalid". For the time being simply reverting back to `perl`.

**Comment by haarg** [comment]
The CPAN-Meta dist now includes copies of the 1.0-1.4 meta specs, with the list of licenses inlined in the documents.  https://metacpan.org/pod/CPAN::Meta::History::Meta_1_4#license
